---
kind: Namespace
apiVersion: v1
metadata:
  name: sock-shop
  annotations:
    net.kubernetes.io/network-policy: |
      {
        "ingress": {
          "isolation": "DefaultDeny"
        }
      }
