apiVersion: v1
kind: Pod
metadata:
  name: network-anomaly-injector
spec:
  containers:
  - name: network-anomaly-injector
    image: alpine:latest
    command:
      - "sh"
    args:
      - "-c"
      - |
        apk add --no-cache iproute2
        tc qdisc add dev ens18 root netem delay 50ms 10ms distribution normal
        sleep infinity
    securityContext:
      privileged: true
    env:
      - name: HOST_NAME
        valueFrom:
          fieldRef:
            fieldPath: spec.nodeName
  hostNetwork: true

# tc qdisc add dev ens18 root netem delay 20ms 10ms distribution normal loss 10%

# sudo tc qdisc del dev ens18 root netem
