apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: network-status-monitor
spec:
  selector:
    matchLabels:
      app: network-status-monitor
  template:
    metadata:
      labels:
        app: network-status-monitor
    spec:
      containers:
      - name: network-status-monitor
        image: alpine:3.13
        command:
        - sh
        - -c
        - |
          apk add --no-cache iputils
          apk add --no-cache net-tools
          while true; do
              sleep 3
              LOSS=$(ping -c 10 192.168.28.88 | grep 'packet loss' | awk -F',' '{print $3}' | awk '{print $1}')
              RTT=$(ping -c 10  192.168.28.88 | awk -F / '/rtt/ {print $5}')
              echo "192.168.28.88 Packet loss: $LOSS, RTT: $RTT"
              LOSS=$(ping -c 10 192.168.28.89 | grep 'packet loss' | awk -F',' '{print $3}' | awk '{print $1}')
              RTT=$(ping -c 10  192.168.28.89 | awk -F / '/rtt/ {print $5}')
              echo "192.168.28.89 Packet loss: $LOSS, RTT: $RTT"
          done
          


